-- AUTO INCREMENT INCREMENT THE VALUE ONE BY ONE ROW WISE

-- CREATE TABLE TRANSECTION2(
--    TRANSECTION_ID INT primary KEY auto_increment,
--    AMOUNT decimal(5,2),
--    TRANSECTION_TIME DATETIME DEFAULT NOW()
--    );
INSERT INTO TRANSECTION2(AMOUNT)
VALUES(450.05);
SELECT * FROM TRANSECTION2

ALTER TABLE TRANSECTION2
AUTO_INCREMENT=1000  -- INTIALIZE FIRST ROW VALUE AUTO_INCREMENT