-- CREATE TABLE STUDENT(
-- ADDMISSION_DATE DATE, 
-- ADDMISSION_TIME TIME,
-- DATE_AND_TIME DATETIME);
 -- INSERT INTO STUDENT 
-- VALUES(current_date(), current_time(), now()); /*AUTO FILL THE DATA IN SURRENT DATE & TIME*/
-- INSERT INTO  STUDENT
-- VALUES(current_date()+1, current_time()+1, now());
-- DELETE FROM STUDENT;
SELECT * FROM STUDENT;