-- CREATE TABLE TRANSECTION(
--   TRANSECTION_ID INT primary KEY,
--   AMOUNT decimal(5,2),
--   TRANSECTION_TIME DATETIME DEFAULT NOW()
--   );
-- INSERT INTO transection(TRANSECTION_ID,AMOUNT)
-- VALUES(1001,46.6)
sELECT * FROM TRANSECTION

