-- CREATE TABLE PRODUCT(PRODUCT_ID INT,
--      PRODUCT_NAME VARCHAR(100),
--      PRICE DECIMAL(4,2));

-- ALTER TABLE PRODUCT /*ONLY ADD THE UNIQUE PRODUCT_NAME NOT ENTRY DUPLICATE PRODUCT_NAME*/
-- ADD constraint
-- UNIQUE(PRODUCT_NAME);

-- INSERT INTO PRODUCT
-- VALUES(109,'SAREE',10),
-- 	  (110,'KURTI',70), 
--       (111,'SHIRT',90);
-- INSERT INTO PRODUCT   /*USING UNIQUE FUNCTION SO DO NOT ADD DUPLICATE PRODUCT*/
-- VALUES(109,'SAREE',10),
      
-- CREATE TABLE PRODUCTS(PRODUCT_ID INT, /*ANOTHER WAY USING UNIQUE FUNCTION*/
--       PRODUCT_NAME VARCHAR(100)unique,
--       PRICE DECIMAL(4,2));
      
-- INSERT INTO PRODUCTS
--  VALUES(109,'SAREE',10),
--  	  (110,'KURTI',70), 
--        (111,'SHIRT',90);
 -- INSERT INTO PRODUCT   
--  VALUES(109,'SAREE',10),

-- CREATE TABLE PRODUCTS(PRODUCT_ID INT, /*PRICE COLUMN DOESNOT CONTAIN NULL*/
--       PRODUCT_NAME VARCHAR(100),
--       PRICE DECIMAL(6,3)NOT NULL);

-- INSERT INTO PRODUCTS
--  VALUES(109,'SAREE',10),
--  	  (110,'KURTI',NULL), 
--        (111,'SHIRT',90);
--  


      
      
      
      
    
    